### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [8398a7/abilitysheet#1127]
First of all, thanks for Ability Sheet!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/abilitysheet/pulls). I'll port the `peek-performance_bar` one across to this repo now - looks like you're up-to-date on everything else!

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by 8398a7** [comment]
Thanks for the suggestion.
I merged the issued PR, but I noticed that there was one problem and discarded it.
This repository has merging to master as development only.
Is it possible to specify a branch to issue PR when using Dependabot?
If I can publish PR for develop, I will use it.

**Comment by greysteil** [comment]
You can! If will use your default branch by default, but you can customise that by clicking the cog icon when adding a repo.

**Comment by 8398a7** [comment]
Thank you, I will try again
