### ISSUE TITLE
スマホ時ツイートボタンが使用できない

### ISSUE THREAD

**Issue by mitixx** [8398a7/abilitysheet#1175]
不具合に関するIssueです。

【再現手順】

スマホ時にツイートボタンを押すと
403 Forbidden: The server understood the request, but is refusing to fulfill it.
が発生。
（トップページ/マイページいずれのページのツイートボタンも同様の
403が返ってきます）

【発生環境】

iPhoneX
iOS12.1.2
Safari

よろしくお願いします。

**Comment by 8398a7** [comment]
報告ありがとうございます。
こちらでも同様の手順を試してみたのですが、いずれも再現しませんでした。。

もう少し詳細を追ってみたいと思うので以下のものをいただけないでしょうか

- 403が出たときのスクリーンショット
- 403が出たときのURL

こちらのサーバのエラーログも見たのですが、こちらには何も出ていなかったことから
ツイッター側でなにかエラーが出ているのではないかと推測しています。

**Comment by mitixx** [comment]
改めて検証したため、更に発生状況を報告します。
![tw403](https://user-images.githubusercontent.com/22006670/52105977-32908e00-2634-11e9-99d7-3a3c597e9557.gif)
【403エラー発生URL】
マイページ ツイート
https://twitter.com/intent/tweet?hashtags=iidx12&original_referer=https%3A%2F%2Fiidx12.tk%2F&ref_src=twsrc%5Etfw&related=IIDX_12%2CIidxScoreTable&text=DJ.PC.COM%20☆12ノマゲ参考表(未クリア305)&tw_p=tweetbutton&url=https%3A%2F%2Fiidx12.tk%2Fsheets%2F4894-3056%2Fclear%3Freverse_sheet%3Dtrue&via=IIDX_12

マイページ @IIDX_12さんへツイートするボタン
https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fiidx12.tk%2F&ref_src=twsrc%5Etfw&screen_name=IIDX_12&text=不具合報告や機能要望等をお書きください&tw_p=tweetbutton

リロードしても403が発生します。
スコアツールへのログイン／ログアウト試行後も同様に403が発生、持続。
なおブラウザキャッシュを消去するとボタンが回復
(※ただしキャッシュ消去後再度Twitterにあらかじめログインしている場合に@IIDX_12さんへ〜ボタンのみ同様の403が発生 未ログイン時は発生しません)

また、キャッシュ消去後Twitterへログインし、一定時間スコアツールを操作するとすべてのツイートボタンが動画同様の403になります。

発生条件としてはキャッシュおよびTwitterにログインして時間が経過している場合にすべてのツイートボタンが使用不可になる模様。

すべてのツイートボタンが使用不可になってしまうことについてはキャッシュとの関連およびユーザー認証が考えられると思います。
似た事例としてTwitterのOAuth実装（参考URL：https://stackoverflow.com/questions/11792824/twitter-authentication-403-forbidden-the-server-understood-the-request-but-i）
がTwitterが403の今回のエラーを返すものとしてあるようです。
（ログイン状態等の発生条件が非常に似ています）

**Comment by 8398a7** [comment]
こちらの手元でも確認したのですが、mobile safariだけで発生する症状のようですね。。
chromeあるいはmacOS上のsafariでは再現しませんでした。

stackoverflowの例も拝見したのですがtweetボタンはただの静的なaタグによって作られているものなので、callback周りの指定は関係なさそうには思いました。

そしていろいろと試していると、そのうちネイティブアプリが立ち上がる、chromeと同じ挙動になってしまいました。。
![](https://user-images.githubusercontent.com/8043276/52161484-c9c71580-2708-11e9-9bdb-f9cc3e152731.gif)
開発者ツールで403画面が出たときのリクエスト内容の詳細(headerやresponse bodyの詳細)を見たかったのですが、上記の通り再現しなくなってしまったので再現できたらまたキャプチャしておこうと思います。
全部戻したつもりですが、コンテンツポップアップブロックやアドブロック周りをいじっていたらいつの間にかネイティブアプリが立ち上がるようになっていました。

**Comment by 8398a7** [comment]
こちら直ってると思うので閉じますがもし再現するようだったらreopenお願いします :bow:
