### ISSUE TITLE
yarn移行

### ISSUE THREAD

**Issue by 8398a7** [8398a7/abilitysheet#803]
deployタイムが減るので優先的に

**Comment by 8398a7** [comment]
サーバ側のnodeを6.9以上にしとかないとだめかも

**Comment by 8398a7** [comment]
node v7.2.1とbowerを入れた。ついでにrubyも2.3.3にする

**Comment by 8398a7** [comment]
対象サーバにyarn導入

**Comment by 8398a7** [comment]
本文にclose書いてもcloseされなくなったのか。。。

**Comment by MaxMEllon** [comment]
fixed だと 自動で close されました

refs : https://github.com/MaxMEllon/.vim/issues/7

**Comment by 8398a7** [comment]
タイトルだとcloseでもいけた。
closesとかその辺も調査する必要がありそうな感じですね。
っていうか普通にバグかもしれない
