### ISSUE TITLE
指定BP以上に星をつける機能の、フォームの不具合

### ISSUE THREAD

**Issue by Nersch** [8398a7/abilitysheet#892]
こんにちは。 いつも利用しております。

指定BP以上に★をつけるというフォームの件についてなのですが

数値以外を誤って入力すると、NaNと表示され値の変更が出来なくなる現象を確認いたしました。

確認端末はiphone6、ios10.2、safari です。

再現確認よろしくお願いします。

**Comment by 8398a7** [comment]
ありがとうございます。
近日中に修正したいと思います。
